language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- export BUILD_LIFE=${TRAVIS_COMMIT:0:7}
- ant run-tests
script:
- ant -DbuildLife=${BUILD_LIFE}
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
- openjdk6
notifications:
  slack:
    secure: yLIMQ+WKVrZWAkPokrT/xN+imfgvLIbgPPcZ0Ytv8/CN0qIRYFf6HEBSnfndIRufNJr2OtPi+3f5i1Lbx21Q6N4d80htGI4E85lTBmCtbwEW6hbcWNu41C5zJocJ5YfPWB/B6Iyqi5GBpOm+o4zE8sYQ+6PY5pMlm6BuiPIGXqVh705oyIoey5gZONBY48ozkB3ymNStRJdp4/NBUN83TAC0WDEf8eRjQlxnvN3rRWn1wtguFHvJ6BnfKSSb7bozSYZ273OOakAcZPmv63Bwo1vnaGFy3PQKSDvgEPTtAGpPjyJMZpqN2jFTI1Vt2sdTMxlJjQVqE7x8P95z3ZNYVDyvXS7/Fatgy5eRATh1tG9Tm6MrMFFyfJSjgEGq6hl4ptak8ANa7XLYMrLSMstESiD3mkeVca489wMtDaqfj3OoxS1k/AhBZnjO2EJX/enwOuW5l0Ve5yFT8x93bAAp7r90qRppmsJBfHZ/bFFbFINey9Ao+uE/aTH2OvdEQPBfZOVhpDNFOFhRcNWUsuR2bQPwyMsxx4PrFLF+JpxcjM/5Ey9P7e/j3wbTF8OFSgdbuvmdCJzd4PBd47Bc4ZzSkxCdnenKUWg5uqn3Mj+c44NXFhxMT5raqmHCCEoKRvwM53MLh0bsyLdez3k82/oDFbemb5ZAluxr1qa/RN+RKU0=
    on_success: change
    on_failure: change
  email: false
deploy:
  provider: releases
  api_key:
    secure: S7nz9uT7x7aG735q02A+EgLDQSe3rbNnELggsOWw8hFfC5447KGiVjZ5DvUtydgeBLL43V6NXfKc+GeGC7Ck21JEt3jVOGIjugniMu8fNdpCZmq6Bq6ZwKJX6Gvk7k2PZK2oyThgwznRot5yxOXVfWkafU+fHxomzWr+eP0RP+4YZDVZ5uvdGbqsT+ZteVu0bNTsaxTeVmapIv9AHGqJzwcHES0BCsy5DZXRiiuLLPV9Tr71VtvXEKPshxyqSpj6nNFN8hdKph0w3AVazgpJNqhc7K1bMKvM1VcVL+XxMYyw6Of/ty5NY/0oqsPDLUEEwYRIvTWq4bnwkg77PKdJKcnINxwoqVlBUlujDMfzGLI5bfF7sGb7fuimSd8Nof0F5n6e8Y3Y02FonAeAe4YtT1EfasvXBD4gBYllciNuCj/LN8k7aMQe6Le15/Dew+fTJaTOMo+q65JwCgtXO6iXgURcB4/+f/vDb0CaXFitwBm73byPVSd9QncbYGNBlPSYf8ZUkC3NWIGj+wTzN9gk+z9SHMZLjHZugLyGjQywouZqczjwfyLiTTdWCi+djVlD5O3sqbX7pMPQKYkcL6WjBd7o183fI2Z66BqDv2k3LQDf6iBBPgNzCSUqbJuTxN4WbaMthh1SkKXWKOSdwq2481rIQHp+LK80J4LDWErvulU=
  file_glob: true
  file: releases/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: IBM-UrbanCode/IBM-MQ-zOS-UCD
